markdown: redcarpet
highlighter: null
permalink: pretty

url: www.abdullahvelioglu.com
baseurl: /blog

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
